### Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for
fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier
transforms, basic linear algebra, basic statistical operations, random simulation and much more

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data
types, with many operations being performed in compiled code for performance. There are several important differences
between NumPy arrays and the standard Python sequences:

• NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size
of an ndarray will create a new array and delete the original.

• The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in
memory.

• NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically,
such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

#### Objectives

• Understand the difference between one-, two- and n-dimensional arrays in NumPy

• Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops

• Understand axis and shape properties for n-dimensional arrays



NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the
same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the
same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less
functionality. 

#### What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in
an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each
dimension.

In NumPy, dimensions are called axes.

In [2]:
import numpy as np

#### Array Creation

There are several ways to create arrays. 

You can create an array from a regular Python list or tuple using the array function. The type of the
resulting array is deduced from the type of the elements in the sequences.

In [122]:
a = np.array([2, 3, 4])
print(a)
lst = [2,3,4,'a']
print(lst)

[2 3 4]
[2, 3, 4, 'a']


In [123]:
a.dtype

dtype('int32')

In [124]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [125]:
b.dtype

dtype('float64')

In [126]:
a = np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into threedimensional arrays, and so on.

In [129]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
print(b[0])
print(type(b))

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[1.5 2.  3. ]
<class 'numpy.ndarray'>


The type of the array can also be explicitly specified at creation time:

In [130]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to
create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function
empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype
of the created array is float64, but it can be specified via the key word argument dtype.


In [133]:
np.zeros((3, 4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [134]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

The function empty creates an array whose initial content is random and depends on the state
of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every
element afterwards!

In [3]:
np.empty((2, 3, 4))

array([[[ 6.73694516e-090,  4.34788612e+199,  3.90428808e+233,
          1.65316193e+098],
        [ 1.51608904e-013, -2.35489353e-310,  4.85674970e-028,
          1.63856525e+248],
        [ 4.85673426e-028,  4.97317159e+247,  7.44590971e+006,
          7.12593715e+059]],

       [[ 9.41170396e+218, -2.40773121e-310,  2.11330627e+214,
          8.25106738e+015],
        [ 2.26155701e+137,  1.36042121e+137,  1.01493487e+137,
          1.32013134e+180],
        [ 2.66457866e+006, -2.45696150e-310,  1.08993511e+016,
          3.95604316e+252]]])

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range,
but returns an array.

In [4]:
np.arange(10, 30, 4)

array([10, 14, 18, 22, 26])

In [5]:
np.arange(0, 2, 0.3) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval

In [11]:
np.linspace(0, 30, num=10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

#### Adding, removing, and sorting elements

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [13]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### shape and size of an array

In [18]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [19]:
array_example.ndim # number of dimensions of the array

3

In [20]:
array_example.size # total number of elements in the array

24

In [21]:
array_example.shape # shape of an array

(3, 2, 4)

#### Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [22]:
a = np.array([20, 30, 40, 50])

In [23]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [25]:
c = a - b
c

array([20, 29, 38, 47])

In [26]:
b*2

array([0, 2, 4, 6])

In [27]:
b**2 # b squared

array([0, 1, 4, 9], dtype=int32)

In [28]:
a < 35

array([ True,  True, False, False])

In [29]:
A = np.array([[1, 1],[0, 1]])

In [30]:
B = np.array([[2, 0],[3, 4]])

In [31]:
A * B

array([[2, 0],
       [0, 4]])

In [32]:
A @ B #metrix product

array([[5, 4],
       [3, 4]])

In [33]:
A.dot(B)

array([[5, 4],
       [3, 4]])

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the
ndarray class.

In [34]:
B

array([[2, 0],
       [3, 4]])

In [38]:
B.sum()

9

In [39]:
B.min()

0

In [40]:
B.max()

4

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by
specifying the axis parameter you can apply an operation along the specified axis of an array:


In [42]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
b.sum(axis=1) # sum of each column

array([ 6, 22, 38])

In [46]:
b.min(axis=1) # min of each row

array([0, 4, 8])

In [47]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

### Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [48]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [50]:
a[2]

8

In [51]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [52]:
# equivalent to a[0:6:2] = 1000
# from start to position 6, exclusive, set every 2nd element to 1000

print(a[:6:2])


[ 0  8 64]


In [53]:
a[:6:2] = 1000
print(a)

[1000    1 1000   27 1000  125  216  343  512  729]


In [54]:
a[::-1] # reversed order

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [55]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [56]:
b = np.array([[ 0, 1, 2, 3],[10, 11, 12, 13],[20, 21, 22, 23],[30, 31, 32, 33],[40, 41, 42, 43]])
print(b.shape)
b

(5, 4)


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [57]:
b[2,3]

23

In [65]:
# each row in the second column of b

b[:,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [66]:
# equivalent to the previous example

b[:, 1] 

array([ 1, 11, 21, 31, 41])

In [67]:
# each column in the second and third row of b

b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

Iterating over multidimensional arrays is done with respect to the first axis:


In [71]:
for row in b.T:
    for i in row:
        print(i)

0
10
20
30
40
1
11
21
31
41
2
12
22
32
42
3
13
23
33
43


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an
iterator over all the elements of the array:

In [72]:
print(b.flat)

In [92]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Changing the shape of an array

An array has a shape given by the number of elements along each axis:

In [73]:
a = np.floor(10 * rg.random((3, 4)))
a

NameError: name 'rg' is not defined

In [74]:
b.shape

(5, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a
modified array, but do not change the original array:

In [76]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [80]:
b.reshape(10, 2)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13],
       [20, 21],
       [22, 23],
       [30, 31],
       [32, 33],
       [40, 41],
       [42, 43]])

In [81]:
b.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [82]:
b.T.shape

(4, 5)

In [84]:
b.shape

(5, 4)